version: '3.8'

services:
  message-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb?sslmode=disable
    depends_on:
      - db
    command: ["sh", "-c", "goose -dir=/app/migrations postgres \"$DATABASE_URL\" up && /app/message-processor"]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
