port: "8000"

db:
    username: "myuser"
    host: "localHost"
    port: "5432"
    dbname: "mydb"
    sslmode: "disable"


development:
  driver: postgres
  open: user=myuser password=mypassword dbname=mydb sslmode=disable